sudo: required
services: docker
script:
        - docker run -it -v /var/run/docker.sock:/var/run/docker.sock ubuntu:latest sh -c "apt-get update ; apt-get install freetds-dev fuse libfuse2 libfuse-dev libattr1-dev libavahi-common-dev make devscripts debhelper pkg-config libunwind-dev clang++-3.7 git make -y ; git clone https://github.com/Microsoft/dbfs.git ; cd dbfs; make package-ubuntu"